[project]
name = 'src'
version = '0.0.1'
description = 'MLOps Project for productionizing models'
authors = [{ name = 'Gavis', email = 'gavis@gmail.com' }]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = ['requirements.txt']}